name             'postinstall'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures postinstall'
long_description 'Installs/Configures postinstall'
version          '0.1.0'
