source "https://supermarket.getchef.com"
cookbook 'apt'
cookbook 'user'
cookbook 'ssh_known_hosts'
cookbook 'preinstall', path: 'site-cookbooks/preinstall'
cookbook 'git'
cookbook 'postgresql', git: 'http://github.com/hw-cookbooks/postgresql'
# cookbook 'mysql', '5.5.3'
cookbook 'database'
cookbook 'ruby_build'
cookbook 'nodejs', git: 'https://github.com/mdxp/nodejs-cookbook'
# cookbook 'rbenv', git: 'https://github.com/RayMangum/chef-rbenv'
cookbook 'rbenv', git: 'https://github.com/fnichol/chef-rbenv'
# cookbook 'nginx'
# cookbook 'postinstall', path: 'site-cookbooks/postinstall'
cookbook 'rails', path: 'site-cookbooks/rails'

