name             'preinstall'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures preinstall'
long_description 'Installs/Configures preinstall'
version          '0.1.0'

depends 'git'
supports 'ubuntu'
